export { default as AppFooter } from './AppFooter.vue'
export { default as AppHeader } from './AppHeader.vue'
export { default as ShowCard } from './ShowCard.vue'
export { default as ShowRecommendations } from './ShowRecommendations.vue'
export { default as ShowRow } from './ShowRow.vue'
